<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Receipt {{ $payment->receipt_number }}</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        @media print {
            .no-print { display: none !important; }
            body { padding: 0 !important; }
        }
    </style>
</head>
<body class="min-h-screen bg-slate-100 px-4 py-10 text-slate-900 antialiased">
    <div class="no-print mx-auto mb-4 max-w-lg text-right">
        <button onclick="window.print()" class="rounded-md bg-brand-navy px-4 py-2 text-sm font-medium text-white hover:bg-brand-navy-light">
            Print / Save as PDF
        </button>
    </div>

    <div class="mx-auto max-w-lg rounded-xl bg-white p-8 shadow-sm ring-1 ring-slate-200">
        <div class="mb-6 flex items-center gap-3 border-b border-slate-200 pb-6">
            <img src="{{ asset('images/logo.png') }}" alt="Rahai School" class="h-14 w-14">
            <div>
                <h1 class="font-serif text-lg font-bold text-brand-navy">Rahai School</h1>
                <p class="text-xs text-slate-500">Yayasan Pendidikan Halmahera Membangun Bangsa</p>
            </div>
        </div>

        <div class="mb-6 flex items-center justify-between">
            <h2 class="font-serif text-xl font-bold text-brand-navy">Payment Receipt</h2>
            <span class="text-sm text-slate-500">{{ $payment->receipt_number }}</span>
        </div>

        <dl class="grid grid-cols-2 gap-y-3 text-sm">
            <dt class="text-slate-500">Student</dt>
            <dd class="text-right text-slate-900">{{ $payment->invoice->student->fullName() }} ({{ $payment->invoice->student->student_number }})</dd>

            <dt class="text-slate-500">Invoice</dt>
            <dd class="text-right text-slate-900">{{ $payment->invoice->invoice_number }}</dd>

            <dt class="text-slate-500">Date Paid</dt>
            <dd class="text-right text-slate-900">{{ $payment->paid_at->format('d M Y') }}</dd>

            <dt class="text-slate-500">Method</dt>
            <dd class="text-right capitalize text-slate-900">{{ str_replace('_', ' ', $payment->method) }}</dd>

            <dt class="text-slate-500">Received By</dt>
            <dd class="text-right text-slate-900">{{ $payment->receivedBy->fullName() }}</dd>
        </dl>

        <div class="mt-6 flex items-center justify-between rounded-lg bg-slate-50 px-4 py-3">
            <span class="text-sm font-semibold text-slate-700">Amount Paid</span>
            <span class="text-lg font-semibold text-brand-navy">Rp {{ number_format($payment->amount, 0, ',', '.') }}</span>
        </div>

        <div class="mt-6 flex items-center justify-between border-t border-slate-100 pt-4 text-sm">
            <span class="text-slate-500">Remaining Balance</span>
            <span class="font-medium {{ $payment->invoice->balance() > 0 ? 'text-red-600' : 'text-emerald-600' }}">
                Rp {{ number_format($payment->invoice->balance(), 0, ',', '.') }}
            </span>
        </div>

        <p class="mt-8 text-center text-xs text-slate-400">This receipt was generated by Rahai School Management System.</p>
    </div>
</body>
</html>
